port: 7890
socks-port: 7891
# mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false  
  listen: 127.0.0.1:1053
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts : true
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
proxies:
  - name: bandwagonhost(å€ç‡1.3-ä¸Šæµ·CN2)
    type: trojan
    server: shct2.forgebukkit.com
    port: 33123
    password: 64375483-bc00-4553-a80f-fa81f9801d88
    udp: true
    sni: www.janeuorg.eu.org
    alpn:
      - h2
      - http/1.1
  - name: bandwagonhost(å€ç‡1-ä¸Šæµ·è”é€š-9929)
    type: trojan
    server: shcu.forgebukkit.com
    port: 44123
    password: 64375483-bc00-4553-a80f-fa81f9801d88
    udp: true
    sni: www.janeuorg.eu.org
    alpn:
      - h2
      - http/1.1
  - name: bandwagonhost(å€ç‡0.8-å¹¿å·ç§»åŠ¨A)
    type: trojan
    server: 36.133.6.84
    port: 33123
    password: 64375483-bc00-4553-a80f-fa81f9801d88
    udp: true
    sni: www.janeuorg.eu.org
    alpn:
      - h2
      - http/1.1
  - name: bandwagonhost(å€ç‡0.8-å¹¿å·ç§»åŠ¨B)
    type: trojan
    server: 112.33.52.65
    port: 33312
    password: 64375483-bc00-4553-a80f-fa81f9801d88
    udp: true
    sni: www.janeuorg.eu.org
    alpn:
      - h2
      - http/1.1
  - name: virmach(å€ç‡1.6-ä¸Šæµ·è”é€š-CN2)
    type: trojan
    server: 139.227.219.199
    port: 11123
    password: 90d29cfe-b4ab-49be-aef6-530eb4974d42
    udp: true
    sni: www.febeuorg.eu.org
    alpn:
      - h2
      - http/1.1
  - name: bandwagonhost(cdn)
    type: vmess
    server: ip.sb
    port: 443
    uuid: 64375483-bc00-4553-a80f-fa81f9801d88
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: bandwagonhost.bylheart.workers.dev
    network: ws
    ws-opts:
      path: /vcndvws
      headers:
        Host: bandwagonhost.bylheart.workers.dev
      max-early-data: 2048
      early-data-header-name: Sec-WebSocket-Protocol
  - name: virmach(cdn)
    type: vmess
    server: hostmonit.com
    port: 443
    uuid: 90d29cfe-b4ab-49be-aef6-530eb4974d42
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    servername: virmach.bylheart.workers.dev
    network: ws
    ws-opts:
      path: /bhfxvws
      headers:
        Host: virmach.bylheart.workers.dev
      max-early-data: 2048
      early-data-header-name: Sec-WebSocket-Protocol
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - auto
      - load-balance
      - bandwagonhost(å€ç‡1.3-ä¸Šæµ·CN2)
      - bandwagonhost(å€ç‡1-ä¸Šæµ·è”é€š-9929)
      - bandwagonhost(å€ç‡0.8-å¹¿å·ç§»åŠ¨A)
      - bandwagonhost(å€ç‡0.8-å¹¿å·ç§»åŠ¨B)
      - virmach(å€ç‡1.6-ä¸Šæµ·è”é€š-CN2)
      - bandwagonhost(cdn)
      - virmach(cdn)
  - name: "auto"
    type: url-test
    proxies:
      - bandwagonhost(å€ç‡1.3-ä¸Šæµ·CN2)
      - bandwagonhost(å€ç‡1-ä¸Šæµ·è”é€š-9929)
      - bandwagonhost(å€ç‡0.8-å¹¿å·ç§»åŠ¨A)
      - bandwagonhost(å€ç‡0.8-å¹¿å·ç§»åŠ¨B)
      - virmach(å€ç‡1.6-ä¸Šæµ·è”é€š-CN2)
      - bandwagonhost(cdn)
      - virmach(cdn)
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: "load-balance"
    type: load-balance
    proxies:
      - bandwagonhost(å€ç‡1.3-ä¸Šæµ·CN2)
      - bandwagonhost(å€ç‡1-ä¸Šæµ·è”é€š-9929)
      - bandwagonhost(å€ç‡0.8-å¹¿å·ç§»åŠ¨A)
      - bandwagonhost(å€ç‡0.8-å¹¿å·ç§»åŠ¨B)
      - virmach(å€ç‡1.6-ä¸Šæµ·è”é€š-CN2)
      - bandwagonhost(cdn)
      - virmach(cdn)
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
rule-providers:
# å…¨çƒç›´è¿
  LocalAreaNetwork:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.yaml
    interval: 86400
# å…¨çƒç›´è¿
  UnBan:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
    path: ./ruleset/UnBan.yaml
    interval: 86400
# å¹¿å‘Šæ‹¦æˆª
  BanAD:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: ./ruleset/BanAD.yaml
    interval: 86400
# åº”ç”¨å‡€åŒ–
  BanProgramAD:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    path: ./ruleset/BanProgramAD.yaml
    interval: 86400
# AdBlock
  BanEasyList:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
    path: ./ruleset/BanEasyList.yaml
    interval: 86400
# AdBlock
  BanEasyListChina:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
    path: ./ruleset/BanEasyListChina.yaml
    interval: 86400
# éšç§é˜²æŠ¤
  BanEasyPrivacy:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
    path: ./ruleset/BanEasyPrivacy.yaml
    interval: 86400
# è°·æ­ŒFCM
  GoogleFCM:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
    path: ./ruleset/GoogleFCM.yaml
    interval: 86400
# è°·æ­ŒğŸ‡¨ğŸ‡³PlayæœåŠ¡
  GoogleCNProxyIP:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
    path: ./ruleset/GoogleCNProxyIP.yaml
    interval: 86400
# è°·æ­ŒğŸ‡¨ğŸ‡³
  GoogleCN:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
    path: ./ruleset/GoogleCN.yaml
    interval: 86400
# è°·æ­Œ
  Google:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
    path: ./ruleset/Google.yaml
    interval: 86400
# å…¨çƒç›´è¿
  SteamCN:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
    path: ./ruleset/SteamCN.yaml
    interval: 86400
# å¾®è½¯äº‘ç›˜
  OneDrive:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
    path: ./ruleset/OneDrive.yaml
    interval: 86400
# å¾®è½¯æœåŠ¡
  Microsoft:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
    path: ./ruleset/Microsoft.yaml
    interval: 86400
# è‹¹æœæœåŠ¡
  Apple:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Apple.list
    path: ./ruleset/AppleCN.yaml
    interval: 86400
# ç”µæŠ¥æ¶ˆæ¯
  Telegram:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    path: ./ruleset/Telegram.yaml
    interval: 86400
# ç½‘æ˜“éŸ³ä¹
  NetEaseMusic:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
    path: ./ruleset/NetEaseMusic.yaml
    interval: 86400
# æ¸¸æˆå¹³å°
  Epic:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
    path: ./ruleset/Epic.yaml
    interval: 86400
# æ¸¸æˆå¹³å°
  Sony:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
    path: ./ruleset/Sony.yaml
    interval: 86400
# æ¸¸æˆå¹³å°
  Steam:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
    path: ./ruleset/Steam.yaml
    interval: 86400
# æ²¹ç®¡è§†é¢‘
  YouTube:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.yaml
    interval: 86400
# å¥ˆé£è§†é¢‘
  Netflix:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
    path: ./ruleset/Netflix.yaml
    interval: 86400
# å¥ˆé£è§†é¢‘
  AmazonIp:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AmazonIp.list
    path: ./ruleset/AmazonIp.yaml
    interval: 86400
# å·´å“ˆå§†ç‰¹
  Bahamut:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
    path: ./ruleset/Bahamut.yaml
    interval: 86400
# å“”å“©å“”å“©
  BilibiliHMT:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
    path: ./ruleset/BilibiliHMT.yaml
    interval: 86400
# å“”å“©å“”å“©
  Bilibili:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
    path: ./ruleset/Bilibili.yaml
    interval: 86400
# å›½å†…åª’ä½“
  ChinaMedia:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
    path: ./ruleset/ChinaMedia.yaml
    interval: 86400
# å›½å¤–åª’ä½“
  ProxyMedia:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
    path: ./ruleset/ProxyMedia.yaml
    interval: 86400
# èŠ‚ç‚¹é€‰æ‹©
  ProxyGFWlist:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
    path: ./ruleset/ProxyGFWlist.yaml
    interval: 86400
# å…¨çƒç›´è¿
  ChinaIp:
    type: http
    behavior: ipcidr
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
    path: ./ruleset/ChinaIp.yaml
    interval: 86400
# å…¨çƒç›´è¿
  ChinaDomain:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.yaml
    interval: 86400
# å…¨çƒç›´è¿
  ChinaCompanyIp:
    type: http
    behavior: ipcidr
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.yaml
    interval: 86400
# å…¨çƒç›´è¿
  Download:
    type: http
    behavior: classical
    url: https://raw.fastgit.org/ACL4SSR/ACL4SSR/master/Clash/Download.list
    path: ./ruleset/Download.yaml
    interval: 86400
# è‡ªå®šä¹‰
  MyRules:
    type: http
    behavior: domain
    url: https://raw.fastgit.org/bylheart/clash/main/MyRules.txt
    path: ./ruleset/MyRules.yaml
    interval: 86400
rules:
  - RULE-SET,MyRules,PROXY
# æ‹’ç»
#  - RULE-SET,BanAD,REJECT
#  - RULE-SET,BanProgramAD,REJECT
#  - RULE-SET,BanEasyList,REJECT
#  - RULE-SET,BanEasyListChina,REJECT
#  - RULE-SET,BanEasyPrivacy,REJECT
# ç›´è¿
  - RULE-SET,LocalAreaNetwork,DIRECT
  - RULE-SET,UnBan,DIRECT
  - RULE-SET,GoogleFCM,DIRECT
  - RULE-SET,GoogleCN,DIRECT
  - RULE-SET,OneDrive,DIRECT
  - RULE-SET,Microsoft,DIRECT
  - RULE-SET,Apple,DIRECT
  - RULE-SET,NetEaseMusic,DIRECT
  - RULE-SET,Epic,DIRECT
  - RULE-SET,Sony,DIRECT
  - RULE-SET,Steam,DIRECT
  - RULE-SET,BilibiliHMT,DIRECT
  - RULE-SET,Bilibili,DIRECT  
  - RULE-SET,ChinaMedia,DIRECT
  - RULE-SET,ChinaIp,DIRECT
  - RULE-SET,ChinaDomain,DIRECT
  - RULE-SET,ChinaCompanyIp,DIRECT
  - RULE-SET,Download,DIRECT
# ä»£ç†
#  - RULE-SET,GoogleCNProxyIP,PROXY
#  - RULE-SET,YouTube,PROXY
#  - RULE-SET,Google,PROXY
#  - RULE-SET,Telegram,PROXY
#  - RULE-SET,Netflix,PROXY
#  - RULE-SET,AmazonIp,PROXY
#  - RULE-SET,Bahamut,PROXY
#  - RULE-SET,ProxyMedia,PROXY
#  - RULE-SET,ProxyGFWlist,PROXY
# å…¶ä»–
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,PROXY
